version: "2"

volumes:
    go2rtc-data:
services:
  go2rtc:
    container_name: go2rtc
    image: alexxit/go2rtc
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - "go2rtc-data:/config"   # folder for go2rtc.yaml file (edit from WebUI)