name: Release
description: 'Run Semantic-Release'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

outputs:
  NEW_RELEASED_VERSION: ${{ steps.semantic.outputs.new_release_version }}

runs:
  using: 'composite'
  steps:
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec@6.0.3
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}