name: Deploy With Balena

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application
        uses: actions/checkout@v4
      - id: release_step
        uses: ./.github/actions/release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      newReleaseVersion: ${{ steps.release_step.outputs.NEW_RELEASED_VERSION }}
  pushToBalena:
    needs: release
    name: Deploy with Balena
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application
        uses: actions/checkout@v4
        with:
          ref: ref: ${{ github.ref }}
      - name: Deploy with Balena
        run: .github/scripts/deploy-balena.sh
        env:
          BALENA_TOKEN: ${{ secrets.BALENA_TOKEN }}
          FLEET: ${{ secrets.BALENA_FLEET }}
          NEW_RELEASED_VERSION: ${{ needs.release.outputs.newReleaseVersion }}